remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - CONTRIBUTING.md
#   - README.md
#   - LICENSE.md
#   - COPYING.md
#   - CODE_OF_CONDUCT.md
#   - CONTRIBUTING.md
#   - ISSUE_TEMPLATE.md
#   - PULL_REQUEST_TEMPLATE.md
title: meteoc's notebook
description: 天气轮的笔记本
#theme: jekyll-theme-cayman

show_downloads: true
google_analytics:

# github:
# zip_url: http://example.com/download.zip
# another_url: another value